Automotora/urls.py
# automotora/urls.py (archivo principal del proyecto)
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),          
    path('vehiculos/', include('vehiculos.urls')),       # URL de inicio # URLs de 'vehiculos'  # URLs de 'reservas'     # URLs de 'compras'
    path('usuarios/', include('usuarios.urls')),    # URLs de 'usuarios'
    path('repuestos/', include('repuestos.urls')),
    path('', include('transaccion.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]    

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
# home/urls.py
from django.urls import path
from . import views

app_name = 'home'  # Define el namespace para esta aplicación

urlpatterns = [
    path('', views.inicio, name='inicio'),  # Define la URL de inicio con el nombre 'inicio'
]

transaccion/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'transaccion'
urlpatterns = [
    path('iniciar-pago/<int:vehiculo_id>/', views.iniciar_pago, name='iniciar_pago'),
    path('webpay-confirmacion/', views.confirmacion_pago, name='confirmacion_pago'),
    path('transaccion/estado/<str:token>/', views.estado_transaccion, name='estado_transaccion'),
    path('cancelar-pago/', views.cancelar_pago, name='cancelar_pago'),
    path('ingresos-totales/', views.vista_total_ingresos, name='vista_total_ingresos'),
    path('ingresos-totales-adm/', views.vista_total_ingresos_adm, name='vista_total_ingresos_adm'),
    path('iniciar-suscripcion/', views.iniciar_suscripcion, name='iniciar_suscripcion'),
    path('confirmacion-suscripcion/<int:suscripcion_id>/', views.confirmacion_suscripcion, name='confirmacion_suscripcion'),
]

usuarios/urls.py
# usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from . import views
app_name = 'usuarios'  # Define el namespace para la aplicación 'usuarios'

urlpatterns = [
    path('perfil/', views.perfil_usuario, name='perfil'),
    path('registro/', views.registro, name='registro'),  # Ejemplo de URL para 'perfil'
    path('login/', LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    #enlaces para recuperar contraseña
]

vehiculos/urls.py
from django.urls import path
from . import views

app_name = 'vehiculos'
urlpatterns = [
    path('<int:id>/', views.detalle_vehiculo, name='detail'),  # Ruta existente
    path('', views.vehiculo_list, name='list'),  # Lista de vehículos
    path('create/', views.vehiculo_create, name='create'),  # Crear vehículo
    path('<int:pk>/update/', views.vehiculo_update, name='update'),  # Actualizar vehículo
    path('<int:pk>/delete/', views.vehiculo_delete, name='delete'),  # Eliminar vehículo
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Usuario(models.Model):
    # Extendiendo el modelo de User en Django o usando ForeignKey a User
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.user.username
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    photo = models.ImageField(upload_to="profile_pics/", default="default_avatar.png")

    def __str__(self):
        return f"Perfil de {self.user.username}"

usuarios/forms.py
# usuarios/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from django.utils.crypto import get_random_string
from .models import Usuario
class RegistroForm(UserCreationForm):
    email = forms.EmailField(required=True, label="Correo")
    rut = forms.CharField(
        required=True,
        max_length=12,
        validators=[
            RegexValidator(
                regex=r"^\d{1,2}\.\d{3}\.\d{3}-[0-9kK]$",
                message="El RUT debe estar en el formato 12.345.678-9",
            )
        ],
        help_text="Formato: 12.345.678-9"
    )
    grupo = forms.ModelChoiceField(queryset=Group.objects.all(), required=True, label="Tipo de Usuario")

    class Meta:
        model = User
        fields = [ "first_name", "last_name", "rut", "email", "password1", "password2", "grupo"]


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = self.cleaned_data["email"]  # Usa el email como username
        if commit:
            user.save()
        # Guarda el campo rut en el perfil de usuario
            Usuario.objects.create(user=user, rut=self.cleaned_data["rut"])
        return user

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import RegistroForm
from django.contrib.auth.decorators import login_required
from transaccion.models import Suscripcion


def perfil_usuario(request):
    # Filtrar la suscripción activa más reciente del usuario
    suscripcion = Suscripcion.objects.filter(propietario=request.user, estado="ACTIVA").order_by('-fecha_inicio').first()

    # Determinar el plan, la fecha de término y el límite de inventario
    if suscripcion:
        if suscripcion.monto == 10000:
            plan = "Plan Básico"
            limite_inventario = 50  # Límite para el plan básico
        elif suscripcion.monto == 20000:
            plan = "Plan Intermedio"
            limite_inventario = 200  # Límite para el plan intermedio
        elif suscripcion.monto == 30000:
            plan = "Plan Avanzado"
            limite_inventario = float('inf')  # Límite ilimitado para el plan avanzado
        else:
            plan = "Plan Desconocido"
            limite_inventario = 0  # Sin límite válido

        fecha_termino = suscripcion.fecha_termino
    else:
        plan = "Sin plan"
        fecha_termino = None
        limite_inventario = "No tiene una suscripción activa"

    return render(request, 'usuarios/perfil.html', {
        'plan': plan,
        'fecha_termino': fecha_termino,
        'limite_inventario': limite_inventario
    })

def registro(request):
    if request.method == "POST":
        form = RegistroForm(request.POST)
        if form.is_valid():
            # Guardar el usuario sin confirmar aún para añadir un username automático
            user = form.save(commit=False)
            
            # Generar un username automático basado en el email
            user.username = form.cleaned_data["email"]  # Usa el correo como username
            
            # Guardar el usuario con el username generado
            user.save()
            
            # Asignar el grupo seleccionado al usuario
            grupo = form.cleaned_data.get('grupo')
            user.groups.add(grupo)
            
            # Iniciar sesión automáticamente después de registrarse (opcional)
            login(request, user)
            
            # Redirige a la página de inicio o a la página deseada
            return redirect('home:inicio')
    else:
        form = RegistroForm()
    return render(request, 'usuarios/registro.html', {'form': form})

@login_required
def perfil(request):
    return render(request, 'usuarios/perfil.html', {'user': request.user})

usuarios/templates/usuarios/login.html
<!-- usuarios/templates/usuarios/login.html -->
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de Sesión</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> 


</head>
<body>
  <nav id="hola" class="navbar navbar-expand-lg fixed-top navbar-scroll">
    <div class="container-fluid">
        
        <!-- Elementos alineados a la izquierda: Vehículos y Repuestos -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vehiculos:list' %}">Vehículos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lista_repuestos' %}">Repuestos</a>
                </li>
            </ul>

            <!-- Elemento central: Liva -->
            <a class="navbar-brand mx-auto" href="{% url 'home:inicio' %}">Liva</a>

            <!-- Elementos alineados a la derecha: Mi cuenta y Cerrar sesión -->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'usuarios:perfil' %}">Mi cuenta</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form action="{% url 'usuarios:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link" style="color: #fff;">
                                Cerrar Sesión
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        <h3>Inicio de Sesión</h3>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Ingresar</button>
        <a id="pass_reset" href="{% url 'usuarios:registro' %}" class="btn btn-link">Registrate</a>
        <a id="pass_reset" href="{% url 'password_reset' %}" class="btn btn-link">Recuperar contraseña</a>

    </form>
    <div class="background-section">
        
    </div>


    
</body>
</html> 

usuarios/templates/usuarios/perfil.html
{% load static %}
{% load grupo_tags %}
<!DOCTYPE html>
<html lang="en">

<head>   
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/perfil.css' %}">  
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}"> 

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Automotora Liva</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  
</head>
<!-- base.html -->


<body>        <!-- Navbar -->
  <nav id="hola" class="navbar navbar-expand-lg fixed-top navbar-scroll">
    <div class="container-fluid">
        
        <!-- Elementos alineados a la izquierda: Vehículos y Repuestos -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vehiculos:list' %}">Vehículos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lista_repuestos' %}">Repuestos</a>
                </li>
            </ul>

            <!-- Elemento central: Liva -->
            <a class="navbar-brand mx-auto" href="{% url 'home:inicio' %}">Liva</a>

            <!-- Elementos alineados a la derecha: Mi cuenta y Cerrar sesión -->
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated and user|pertenece_a_grupo:"Propietario" %}
                  <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'transaccion:iniciar_suscripcion' %}">Suscripción</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'transaccion:vista_total_ingresos' %}">Ingresos</a>
                </li>
                {% endif %}
                {% if user.is_authenticated and user|pertenece_a_grupo:"Administrador" %}
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'transaccion:vista_total_ingresos_adm' %}">Ingresos ADM</a>
                </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'usuarios:perfil' %}">Mi cuenta</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form action="{% url 'usuarios:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link" style="color: #fff;">
                                Cerrar Sesión
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
        <div class="main-content">
            <form class="form1">
                <div class="profile-container">
                     <div class="profile-header">
                        <img src="https://www.w3schools.com/howto/img_avatar.png" alt="Foto de perfil" class="profile-image">
                        <h1>{{user.first_name}}</h1>
                        <p class="user-role">Rol del usuario: {{user.groups.first.name}}</p>
                    </div>
                </div>
                <br>
                <div class="profile-container">
                    <div class="profile-details">
                        <h2>Detalles del Usuario</h2>

                        <p><strong>Nombre:</strong> {{ user.first_name }} {{ user.last_name }} </p>

                        <p><strong>Email:</strong> {{ user.email }}</p>

                        <p><strong>Plan Actual:</strong>{{ plan }}</p>

                        {% if fecha_termino %}
                          <p><strong>Fecha de Término: </strong>{{ fecha_termino|date:"d/m/Y" }}</p>
                        {% else %}
                          <p><strong>Fecha de Término:</strong> No disponible</p>
                        {% endif %} 

                        <p><strong>Límite de Inventario:</strong> 
                          {% if limite_inventario == "inf" %}
                              Ilimitado
                          {% else %}
                              {{ limite_inventario }} vehículos
                          {% endif %}

                      </p>
                    </div>
                </div>
            </form>
        </div>
    
        <div class="background-section">
        
    </div>
    <footer
          class="text-center text-lg-start text-white"
          style="background-color: rgb(34, 31, 31)"
          style="opacity: 95%;"
          >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Automotora
            </h6>
            <p>
              Automotora dedicada a la reserva de vehiculos
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
            <p>
              <a class="text-white">MDBootstrap</a>
            </p>
            <p>
              <a class="text-white">MDWordPress</a>
            </p>
            <p>
              <a class="text-white">BrandFlow</a>
            </p>
            <p>
              <a class="text-white">Bootstrap Angular</a>
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Useful links
            </h6>
            <p>
              <a class="text-white">Your Account</a>
            </p>
            <p>
              <a class="text-white">Become an Affiliate</a>
            </p>
            <p>
              <a class="text-white">Shipping Rates</a>
            </p>
            <p>
              <a class="text-white">Help</a>
            </p>
          </div>

          <!-- Grid column -->
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
            <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-3">

      <!-- Section: Copyright -->
      <section class="p-3 pt-0">
        <div class="row d-flex align-items-center">
          <!-- Grid column -->
          <div class="col-md-7 col-lg-8 text-center text-md-start">
            <!-- Copyright -->
            <div class="p-3">
              © 2020 Copyright:
              <a class="text-white" href="https://mdbootstrap.com/"
                 >MDBootstrap.com</a
                >
            </div>
            <!-- Copyright -->
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
            <!-- Facebook -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="fab fa-facebook-f"></i
              ></a>

            <!-- Twitter -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="bi bi-facebook"></i
              ></a>

            <!-- Google -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="fab fa-google"></i
              ></a>

            <!-- Instagram -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="fab fa-instagram"></i
              ></a>
          </div>
          <!-- Grid column -->
        </div>
      </section>
      <!-- Section: Copyright -->
    </div>
    <!-- Grid container -->
  </footer>

</body>
</html>

    

usuarios/templates/usuarios/registro.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> 

</head>
<body>
  <nav id="hola" class="navbar navbar-expand-lg fixed-top navbar-scroll">
    <div class="container-fluid">
        
        <!-- Elementos alineados a la izquierda: Vehículos y Repuestos -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vehiculos:list' %}">Vehículos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lista_repuestos' %}">Repuestos</a>
                </li>
            </ul>

            <!-- Elemento central: Liva -->
            <a class="navbar-brand mx-auto" href="{% url 'home:inicio' %}">Liva</a>

            <!-- Elementos alineados a la derecha: Mi cuenta y Cerrar sesión -->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'usuarios:perfil' %}">Mi cuenta</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form action="{% url 'usuarios:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="nav-link btn btn-link" style="color: #fff;">
                                Cerrar Sesión
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
        <main>
            <form class="form1" method="post">
                <h3>Registro</h3>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="login-button">Registrarse</button>
            </form>
        </main>
    <div class="background-section">
        
    </div>
</body>
</html> 